name: Playwright API Tests
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-html-report
          path: playwright-report/
      # Upload JUnit XML report
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-test-results
          path: results/test-results.xml

      # Optional: Publish test results to GitHub Actions UI
      - name: Publish Test Results
        if: always()
        uses: mikepenz/action-junit-report@v5
        with:
          files: results/test-results.xml
